const ActionTypes = {
    
    CAT_FILTER_BY_BUDGET_LIMIT_REQ: "CATEGORY_FILTER_BY_BUDGET_LIMIT_REQ",
    CAT_FILTER_BY_BUDGET_LIMIT_OK: "CAT_FILTER_BY_BUDGET_LIMIT_OK",
    CAT_FILTER_BY_BUDGET_LIMIT_X: "CAT_FILTER_BY_BUDGET_LIMIT_X",

    CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
    CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
    CATEGORY_ADD_X: "CATEGORY_ADD_X",

    CATEGORY_ALL_REQ: "CATEGORY_ALL_REQ",
    CATEGORY_ALL_OK: "CATEGORY_ALL_OK",
    CATEGORY_ALL_X: "CATEGORY_ALL_X",

    CATEGORY_DEL_REQ: "CATEGORY_DEL_REQ",
    CATEGORY_DEL_OK: "CATEGORY_DEL_OK",
    CATEGORY_DEL_X: "CATEGORY_DEL_X",
}

export default ActionTypes;