const ActionTypes = {
    ADD_CATEGORY: "ADD_CATEGORY",

    CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
    CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
    CATEGORY_ADD_X: "CATEGORY_ADD_X",
}

export default ActionTypes;